version: '3.1'

services:

  weeklydb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: volkan
      MONGO_INITDB_ROOT_PASSWORD: ayla2017
    ports:
      - 27018:27017
    restart: always
 
  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: volkan
      ME_CONFIG_MONGODB_ADMINPASSWORD: ayla2017
      ME_CONFIG_MONGODB_URL: mongodb://volkan:ayla2017@weeklydb:27017/
    depends_on:
        - weeklydb
    restart: always
      
  weeklyapi:
    build: .
    ports:
        - 5000:80
    depends_on:
        - weeklydb